#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-yetus
Version  : 0.5.0
Release  : 1
URL      : https://github.com/apache/yetus/archive/rel/0.5.0.tar.gz
Source0  : https://github.com/apache/yetus/archive/rel/0.5.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.jar
Source2  : https://repo1.maven.org/maven2/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.pom
Source3  : https://repo1.maven.org/maven2/org/apache/yetus/yetus-project/0.5.0/yetus-project-0.5.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-yetus-data = %{version}-%{release}

%description
<!---
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

%package data
Summary: data components for the mvn-yetus package.
Group: Data

%description data
data components for the mvn-yetus package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/yetus/audience-annotations/0.5.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/yetus/audience-annotations/0.5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/yetus/audience-annotations/0.5.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/yetus/audience-annotations/0.5.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/yetus/yetus-project/0.5.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/yetus/yetus-project/0.5.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.jar
/usr/share/java/.m2/repository/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.pom
/usr/share/java/.m2/repository/org/apache/yetus/yetus-project/0.5.0/yetus-project-0.5.0.pom
